name: Using Vale to test Docusaurus source Markdown

on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses:: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1
      with:
        files: __onlyModified
        onlyAnnotateModifiedLines: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

